### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by kevinthedang** [kevinthedang/discord-ollama#117]
## Issue
* Branches can just be whatever they want to be in the repo. Slap a name and it's a branch.
* Contributing.md has no information on branch naming conventions.

## Solution
* Update `CONTRIBUTING.md` to include branch naming conventions
* For example, #10 would have a branch called `feature/user-preference`
  * We can also create some workflows to allow Pull Requests to automatically have the correct initial labels

## References
Sample for CI:
```yml
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
      - 'feature/**'
      - 'releases/**'
```
