### ISSUE TITLE
Actions Workflow(s)

### ISSUE THREAD

**Issue by JT2M0L3Y** [kevinthedang/discord-ollama#24]
## Feature
* Automate testing (when written), potentially automate release delivery to bot server.

## Thoughts
* fairly new concept to the devs; however, not out of the question.

**Comment by kevinthedang** [comment]
Going to mention #14 as this will be a replacement for it to ensure the production version is working as intended

We still could use code coverage so we can even reopen the issue as needed in the future

**Comment by JT2M0L3Y** [comment]
## Continuous Deployment (CD)

With the intention of having this tool run autonomously, having little or no intervention needed, it would be nice to have a workflow that deploys this bot and all its dependencies over to hosting server.

Ideally, this would involve scp or ssh to transfer the files between the workflow runner and the hosting server.

### Requirements
- ssh key pair
- scp action (copy), ssh action (install)

**Comment by JT2M0L3Y** [comment]
GitHub Docs has a number of available endpoints for pulling a version of the project over to a server.
Namely, a "Get the latest release" API endpoint at [this link](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#get-the-latest-release).

**Comment by kevinthedang** [comment]
@JT2M0L3Y

Another thing to consider is having some tests to run on Pull Request so the branch can be validated for the next released feature it has. Go [here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request)

### PR that was Merged
```yml
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
```

### PR that was Opened based on name and files
```yml
on:
  pull_request:
    types:
      - opened
    branches:
      - 'releases/**'
    paths:
      - '**.js'
```

### Reviewed Pull Request
```yml
on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
```
