### ISSUE TITLE
Asynchronous Chat Generation

### ISSUE THREAD

**Issue by kevinthedang** [kevinthedang/discord-ollama#43]
## Idea
* As of version `v0.4.0`, chat's with the bot are "synchronous" meaning it is a handshake process to get the bot to talk,

![image](https://github.com/kevinthedang/discord-ollama/assets/77701718/88b10b70-dde6-4711-8701-a399ef962416)

* It would be interesting to see how the bot can work asynchronously. That is, given access to chat in any channel that is not labeled as `private` on discord.
* So, if there was a conversation between many people about something like TypeScript, bugs, etc, then the bot would try to figure out whether or not to join the chat.
* Essentially, it's message history becomes some arbitrary amount of messages when it decides to start talking.

## Example?
```yml
...

user1: some message about some topic

user2: some message about the same topic

Discord bot: provides some message or input on the topic

...
```
