### ISSUE TITLE
Remove Deployment to Docker Hub and Create Deployment for Remote Server

### ISSUE THREAD

**Issue by kevinthedang** [kevinthedang/discord-ollama#99]
## Issue
* When deploying the image to docker hub, there is no `BOT_TOKEN` or `GUILD_ID` provided for the image to be usable.
* Usage is not interrupted, but the docker hub is not usable unless some solution is given.

## Solution
* Investigate what should be done to make this image accessible and easy to use. Likely we need to reduce env variables but these two are sadly necessary for the bot to function.
* How can we make this image usable when pulled? Does a universal application need to be made? Not sure.
* Also, add proper documentation on what to do when a solution is provided.
  * `docker pull` documentation
  * New setup instructions?

## References
* `release.yml` file for pushing to docker hub
```yml
name: release
run-name: Release Docker Image
on:
  push:
    tags:
      - 'v*'

jobs:
  Deploy-Image:
    runs-on: ubuntu-latest
    environment: release
    timeout-minutes: 3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node Environment lts/hydrogen
        uses: actions/setup-node@v4
        with:
          node-version: lts/hydrogen
          cache: "npm"

      - name: Create Environment Variables
        run: |
          touch .env
          echo CLIENT_TOKEN = NOT_REAL_TOKEN >> .env
          echo GUILD_ID = 123456 >> .env
          echo MODEL = ${{ secrets.MODEL }} >> .env
          echo CLIENT_UID = ${{ secrets.CLIENT_UID }} >> .env
          echo OLLAMA_IP = ${{ secrets.OLLAMA_IP }} >> .env
          echo OLLAMA_PORT = ${{ secrets.OLLAMA_PORT }} >> .env

      - name: Get Version from package.json
        run: echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV
      
      - name: Build Image
        run: |
          npm run docker:build

      - name: Build Image as Latest
        run: |
          npm run docker:build-latest
      
      - name: Log into Docker
        run: |
          docker login --username ${{ vars.DOCKER_USER }} --password ${{ secrets.DOCKER_PASS }}

      - name: Release Docker Image
        run: |
          docker push ${{ vars.DOCKER_USER }}/discord-ollama:${{ env.VERSION }}
          docker push ${{ vars.DOCKER_USER }}/discord-ollama:latest
```

**Comment by kevinthedang** [comment]
Did some extra thinking:

The `Dockerfile` might have to change to allow the image to be usable unless there is a way to modify the image locally and allow a user to have their own `BOT_TOKEN` and `GUILD_ID`.

```dockerfile
# use node LTS image for version 18
FROM node:hydrogen-alpine

# set working directory inside container
WORKDIR /app

# copy package.json and the lock file into the container, and src files
COPY ./src ./src
COPY ./*.json ./
COPY ./.env ./

# install dependencies, breaks
RUN npm install

# build the typescript code
RUN npm run build

# start the application
CMD ["npm", "run", "prod"]
```

**Comment by kevinthedang** [comment]
Gonna be realistic, we should probably just not make this Image public.

We would have to either make this a service that is public on discord and that is not the point of the project. It's supposed to be self-hosted by the user.

We can change the deployment script to point to somewhere we want the image with the associated `BOT_TOKEN`. We just need to make the Image private somehow and only allow us to pull it.

If we can't do that, scrap deploying to an image hub and just deploy it to a server.

cc: @JT2M0L3Y

**Comment by kevinthedang** [comment]
## Updated Issue
* Deploying the image with essential credentials to the public is just a no-no.

## Solution
* Investigate if we can just create a deployment script that will deploy to a given server, we want to host the bot ourselves.
* The server location should be an environmental secret in the project.
* This deployment will be the bot running in a particular Discord Server for use.

## Extra
* The school server would be a nice candidate for this job. It would be great if we had some kind of permissions to deploy and host the bot on there since it's powerful and unused.

**Comment by JT2M0L3Y** [comment]
I am highly on board with deployment to a server instead of deploying an image to the image hub. 
The inability to remove CLIENT_TOKEN as a necessary variable in the image is a happy coincidence and a surefire reason for not publishing a public image.

**Comment by kevinthedang** [comment]
Non-release requirement. This can be done after without version increment later.

cc: @JT2M0L3Y

**Comment by kevinthedang** [comment]
Idea from a class...

```yml
jobs:
  Deploy:
    runs-on: [self-hosted, linux, CPSC334]
    timeout-minutes: 2      # run job for 2 minutes
    steps:
        - name: Check out repository code
          uses: actions/checkout@v4

        - name: Build Debian Package
          run: |
            make build-deb
        
        - name: Copy Debian via ssh password
          uses: appleboy/scp-action@v0.1.7
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            source: "counter-v2.0.0.deb"
            target: /tmp/

        - name: executing remote ssh commands
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            script: sudo dpkg -i /tmp/counter-v2.0.0.deb
```
